# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Google_Map_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Google_Map_ios
    pod 'GoogleMaps'
    pod 'GooglePlaces'


end
