# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Facebook_firebase_login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Facebook_firebase_login

    pod 'Firebase/Auth'

    pod 'FBSDKLoginKit'

    pod 'FacebookLogin'
    pod 'FacebookCore'

end
