# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Google_Sign_in' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Google_Sign_in
   pod 'Firebase/Auth'
   pod 'GoogleSignIn'

end
