# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseFb101' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseFb101
    pod 'FacebookCore'
    pod 'FacebookLogin'
# pod 'Facebook/'
# pod 'Facebook/'

end
